-- Family Travel Tracker Database Setup
-- Run this in your PostgreSQL database

-- Drop existing tables if they exist
DROP TABLE IF EXISTS visited_countries, users, countries;

-- Create users table
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(15) UNIQUE NOT NULL,
    color VARCHAR(15)
);

-- Create countries table with sample data
CREATE TABLE countries (
    id SERIAL PRIMARY KEY,
    country_code CHAR(2) NOT NULL UNIQUE,
    country_name VARCHAR(100) NOT NULL
);

-- Create visited_countries table
CREATE TABLE visited_countries (
    id SERIAL PRIMARY KEY,
    country_code CHAR(2) NOT NULL,
    user_id INTEGER REFERENCES users(id),
    UNIQUE(country_code, user_id)
);

-- Insert sample users
INSERT INTO users (name, color) VALUES 
    ('vikas', 'antiquewhite'),
    ('anant', 'aquamarine'),
    ('jayash', 'azure'),
    ('akash', 'darkcyan');

-- Insert sample countries (major countries)
INSERT INTO countries (country_code, country_name) VALUES 
    ('US', 'United States'),
    ('CA', 'Canada'),
    ('MX', 'Mexico'),
    ('GB', 'United Kingdom'),
    ('FR', 'France'),
    ('DE', 'Germany'),
    ('IT', 'Italy'),
    ('ES', 'Spain'),
    ('NL', 'Netherlands'),
    ('BE', 'Belgium'),
    ('CH', 'Switzerland'),
    ('AT', 'Austria'),
    ('SE', 'Sweden'),
    ('NO', 'Norway'),
    ('DK', 'Denmark'),
    ('FI', 'Finland'),
    ('PL', 'Poland'),
    ('CZ', 'Czech Republic'),
    ('HU', 'Hungary'),
    ('RO', 'Romania'),
    ('BG', 'Bulgaria'),
    ('HR', 'Croatia'),
    ('SI', 'Slovenia'),
    ('SK', 'Slovakia'),
    ('LT', 'Lithuania'),
    ('LV', 'Latvia'),
    ('EE', 'Estonia'),
    ('IE', 'Ireland'),
    ('PT', 'Portugal'),
    ('GR', 'Greece'),
    ('CY', 'Cyprus'),
    ('MT', 'Malta'),
    ('LU', 'Luxembourg'),
    ('IS', 'Iceland'),
    ('RU', 'Russia'),
    ('UA', 'Ukraine'),
    ('BY', 'Belarus'),
    ('MD', 'Moldova'),
    ('GE', 'Georgia'),
    ('AM', 'Armenia'),
    ('AZ', 'Azerbaijan'),
    ('TR', 'Turkey'),
    ('IL', 'Israel'),
    ('LB', 'Lebanon'),
    ('SY', 'Syria'),
    ('JO', 'Jordan'),
    ('IQ', 'Iraq'),
    ('IR', 'Iran'),
    ('AF', 'Afghanistan'),
    ('PK', 'Pakistan'),
    ('IN', 'India'),
    ('BD', 'Bangladesh'),
    ('NP', 'Nepal'),
    ('BT', 'Bhutan'),
    ('LK', 'Sri Lanka'),
    ('MV', 'Maldives'),
    ('CN', 'China'),
    ('JP', 'Japan'),
    ('KR', 'South Korea'),
    ('KP', 'North Korea'),
    ('MN', 'Mongolia'),
    ('VN', 'Vietnam'),
    ('LA', 'Laos'),
    ('KH', 'Cambodia'),
    ('TH', 'Thailand'),
    ('MY', 'Malaysia'),
    ('SG', 'Singapore'),
    ('ID', 'Indonesia'),
    ('PH', 'Philippines'),
    ('BR', 'Brazil'),
    ('AR', 'Argentina'),
    ('CL', 'Chile'),
    ('PE', 'Peru'),
    ('CO', 'Colombia'),
    ('VE', 'Venezuela'),
    ('EC', 'Ecuador'),
    ('BO', 'Bolivia'),
    ('PY', 'Paraguay'),
    ('UY', 'Uruguay'),
    ('GY', 'Guyana'),
    ('SR', 'Suriname'),
    ('AU', 'Australia'),
    ('NZ', 'New Zealand'),
    ('FJ', 'Fiji'),
    ('PG', 'Papua New Guinea'),
    ('ZA', 'South Africa'),
    ('EG', 'Egypt'),
    ('NG', 'Nigeria'),
    ('KE', 'Kenya'),
    ('ET', 'Ethiopia'),
    ('TZ', 'Tanzania'),
    ('UG', 'Uganda'),
    ('GH', 'Ghana'),
    ('CI', 'Ivory Coast'),
    ('SN', 'Senegal'),
    ('ML', 'Mali'),
    ('BF', 'Burkina Faso'),
    ('NE', 'Niger'),
    ('TD', 'Chad'),
    ('SD', 'Sudan'),
    ('LY', 'Libya'),
    ('TN', 'Tunisia'),
    ('DZ', 'Algeria'),
    ('MA', 'Morocco'),
    ('MR', 'Mauritania'),
    ('DJ', 'Djibouti'),
    ('SO', 'Somalia'),
    ('ER', 'Eritrea'),
    ('SS', 'South Sudan'),
    ('CF', 'Central African Republic'),
    ('CM', 'Cameroon'),
    ('GQ', 'Equatorial Guinea'),
    ('GA', 'Gabon'),
    ('CG', 'Republic of the Congo'),
    ('CD', 'Democratic Republic of the Congo'),
    ('AO', 'Angola'),
    ('ZM', 'Zambia'),
    ('ZW', 'Zimbabwe'),
    ('BW', 'Botswana'),
    ('NA', 'Namibia'),
    ('LS', 'Lesotho'),
    ('SZ', 'Eswatini'),
    ('MG', 'Madagascar'),
    ('MU', 'Mauritius'),
    ('SC', 'Seychelles'),
    ('KM', 'Comoros'),
    ('CV', 'Cape Verde'),
    ('GW', 'Guinea-Bissau'),
    ('GN', 'Guinea'),
    ('SL', 'Sierra Leone'),
    ('LR', 'Liberia'),
    ('TG', 'Togo'),
    ('BJ', 'Benin'),
    ('ST', 'Sao Tome and Principe'),
    ('MZ', 'Mozambique'),
    ('MW', 'Malawi'),
    ('RW', 'Rwanda'),
    ('BI', 'Burundi');

-- Insert some sample visited countries for testing
INSERT INTO visited_countries (country_code, user_id) VALUES 
    ('US', 1),
    ('CA', 1),
    ('GB', 2),
    ('FR', 2),
    ('DE', 3),
    ('IT', 3),
    ('ES', 4),
    ('NL', 4);

-- Verify the setup
SELECT 'Database setup completed successfully!' as status; 